#!/bin/bash

set -eux

SCRIPT_DIR=$(cd $(dirname $0); pwd)

RELAYER_CONF="$HOME/.yui-relayer"
RLY_BINARY=${SCRIPT_DIR}/../build/yrly
RLY="${RLY_BINARY} --debug"
FIXTURES_DIR=${SCRIPT_DIR}/../fixtures

echo "Generating ${RLY_BINARY} configurations..."

# Ensure ${RLY_BINARY} is installed
if ! [ -x ${RLY_BINARY} ]; then
  echo "Error: ${RLY_BINARY} is not installed." >&2
  exit 1
fi

rm -rf ${RELAYER_CONF} &> /dev/null

TEMPLATE_DIR=configs/templates
CONFIG_DIR=configs/demo
mkdir -p $CONFIG_DIR
jq --arg PS ${TM_ZK_PS} -r '.prover.prover_type = $PS' ${TEMPLATE_DIR}/ibc-0.json.tpl > ${CONFIG_DIR}/ibc-0.json
cp ${TEMPLATE_DIR}/ibc-1.json.tpl ${CONFIG_DIR}/ibc-1.json

${RLY} config init
${RLY} chains add-dir ${CONFIG_DIR}

# A setup for tendermint client

SEED0=$(jq -r '.mnemonic' < ${FIXTURES_DIR}/tendermint/ibc0/key_seed.json)
echo "Key $(${RLY} tendermint keys restore ibc0 testkey "$SEED0") imported from ibc0 to relayer..."
