// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/provers/tendermintzk/config/config.proto

package relay

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProverConfig struct {
	ZkProverAddr       string `protobuf:"bytes,1,opt,name=zk_prover_addr,json=zkProverAddr,proto3" json:"zk_prover_addr,omitempty"`
	StepVerifierDigest string `protobuf:"bytes,2,opt,name=step_verifier_digest,json=stepVerifierDigest,proto3" json:"step_verifier_digest,omitempty"`
	SkipVerifierDigest string `protobuf:"bytes,3,opt,name=skip_verifier_digest,json=skipVerifierDigest,proto3" json:"skip_verifier_digest,omitempty"`
	ProverType         string `protobuf:"bytes,4,opt,name=prover_type,json=proverType,proto3" json:"prover_type,omitempty"`
	TrustingPeriod     string `protobuf:"bytes,5,opt,name=trusting_period,json=trustingPeriod,proto3" json:"trusting_period,omitempty"`
}

func (m *ProverConfig) Reset()         { *m = ProverConfig{} }
func (m *ProverConfig) String() string { return proto.CompactTextString(m) }
func (*ProverConfig) ProtoMessage()    {}
func (*ProverConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_baf01ad3109d9ad3, []int{0}
}
func (m *ProverConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProverConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProverConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProverConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProverConfig.Merge(m, src)
}
func (m *ProverConfig) XXX_Size() int {
	return m.Size()
}
func (m *ProverConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProverConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProverConfig proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ProverConfig)(nil), "relayer.provers.tendermintzk.config.ProverConfig")
}

func init() {
	proto.RegisterFile("relayer/provers/tendermintzk/config/config.proto", fileDescriptor_baf01ad3109d9ad3)
}

var fileDescriptor_baf01ad3109d9ad3 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x5b, 0xff, 0x81, 0x71, 0x4c, 0x28, 0x3b, 0x14, 0x0f, 0x51, 0x54, 0xd0, 0xcb, 0x9a,
	0x89, 0x9f, 0xc0, 0x3f, 0x77, 0x87, 0x88, 0x07, 0x2f, 0x65, 0x6b, 0xde, 0xc5, 0x97, 0x6e, 0x4d,
	0x78, 0x9b, 0x0d, 0xda, 0x4f, 0xe1, 0xc7, 0xda, 0x71, 0x47, 0x8f, 0xda, 0x7d, 0x11, 0x59, 0x1a,
	0x61, 0xe8, 0x29, 0xe1, 0x79, 0x7e, 0xbf, 0x10, 0x1e, 0x36, 0x20, 0x98, 0x8e, 0x2a, 0x20, 0x61,
	0x48, 0x2f, 0x80, 0x4a, 0x61, 0xa1, 0x90, 0x40, 0x33, 0x2c, 0x6c, 0x9d, 0x8b, 0x4c, 0x17, 0x13,
	0x54, 0xfe, 0x48, 0x0c, 0x69, 0xab, 0xa3, 0x0b, 0x6f, 0x24, 0xde, 0x48, 0xb6, 0x8d, 0xa4, 0x45,
	0x4f, 0x7a, 0x4a, 0x2b, 0xed, 0x78, 0xb1, 0xb9, 0xb5, 0xea, 0x79, 0x13, 0xb2, 0xce, 0xd0, 0x59,
	0x0f, 0x0e, 0x8b, 0x2e, 0x59, 0xb7, 0xce, 0xd3, 0xf6, 0xa1, 0x74, 0x24, 0x25, 0xc5, 0xe1, 0x59,
	0x78, 0x7d, 0xf8, 0xdc, 0xa9, 0xf3, 0x96, 0xbb, 0x93, 0x92, 0xa2, 0x01, 0xeb, 0x95, 0x16, 0x4c,
	0xba, 0x00, 0xc2, 0x09, 0x02, 0xa5, 0x12, 0x15, 0x94, 0x36, 0xde, 0x71, 0x6c, 0xb4, 0xe9, 0x5e,
	0x7d, 0xf5, 0xe8, 0x1a, 0x67, 0xe4, 0xf8, 0xdf, 0xd8, 0xf5, 0x46, 0x8e, 0x7f, 0x8d, 0x53, 0x76,
	0xe4, 0xbf, 0x61, 0x2b, 0x03, 0xf1, 0x9e, 0x03, 0x59, 0x1b, 0xbd, 0x54, 0x06, 0xa2, 0x2b, 0x76,
	0x6c, 0x69, 0x5e, 0x5a, 0x2c, 0x54, 0x6a, 0x80, 0x50, 0xcb, 0x78, 0xdf, 0x41, 0xdd, 0xdf, 0x78,
	0xe8, 0xd2, 0xfb, 0xa7, 0xe5, 0x37, 0x0f, 0x96, 0x0d, 0x0f, 0x57, 0x0d, 0x0f, 0xbf, 0x1a, 0x1e,
	0x7e, 0xac, 0x79, 0xb0, 0x5a, 0xf3, 0xe0, 0x73, 0xcd, 0x83, 0xb7, 0x1b, 0x85, 0xf6, 0x7d, 0x3e,
	0x4e, 0x32, 0x3d, 0x13, 0x38, 0xce, 0xfa, 0xa5, 0x9e, 0xa2, 0x44, 0x5b, 0x6d, 0xed, 0xde, 0xaf,
	0xf3, 0xfe, 0x34, 0x13, 0x4a, 0x0b, 0xb7, 0xf4, 0xf8, 0xc0, 0x8d, 0x77, 0xfb, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x5d, 0x4d, 0x49, 0x1c, 0xab, 0x01, 0x00, 0x00,
}

func (m *ProverConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProverConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProverConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TrustingPeriod) > 0 {
		i -= len(m.TrustingPeriod)
		copy(dAtA[i:], m.TrustingPeriod)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.TrustingPeriod)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ProverType) > 0 {
		i -= len(m.ProverType)
		copy(dAtA[i:], m.ProverType)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.ProverType)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SkipVerifierDigest) > 0 {
		i -= len(m.SkipVerifierDigest)
		copy(dAtA[i:], m.SkipVerifierDigest)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.SkipVerifierDigest)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.StepVerifierDigest) > 0 {
		i -= len(m.StepVerifierDigest)
		copy(dAtA[i:], m.StepVerifierDigest)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.StepVerifierDigest)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ZkProverAddr) > 0 {
		i -= len(m.ZkProverAddr)
		copy(dAtA[i:], m.ZkProverAddr)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.ZkProverAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProverConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ZkProverAddr)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.StepVerifierDigest)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.SkipVerifierDigest)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.ProverType)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.TrustingPeriod)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	return n
}

func sovConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConfig(x uint64) (n int) {
	return sovConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProverConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProverConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProverConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZkProverAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZkProverAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StepVerifierDigest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StepVerifierDigest = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SkipVerifierDigest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SkipVerifierDigest = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProverType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProverType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustingPeriod", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrustingPeriod = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfig = fmt.Errorf("proto: unexpected end of group")
)
