name: test
on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true
    name: Contract Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
      - name: Run Forge tests
        run: |
          forge test -vvv

  e2e:
    strategy:
      fail-fast: true
    name: E2E Tests using Relayer
    runs-on: ubuntu-latest
    needs: check
    env:
      TM_ZK_PS: mock
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install npm dependencies
        run: |
          npm install
      - name: build images
        run: |
          make -C ./e2e build-images
      - name: Build relayer
        run: |
          make -C ./e2e yrly
      - name: Start test chains
        run: |
          make -C ./e2e network deps setup
      - name: Run E2E tests
        run: |
          make -C ./e2e test
